# Tipos de Mensajes
MSG_LOGIN = "LOGIN"
MSG_NEW_VISIT = "NEW_VISIT"       
MSG_REPLICATE_INSERT = "REP_INS"  
MSG_QUERY = "QUERY"               
MSG_OK = "OK"
MSG_ERROR = "ERROR"

# Estados de Recursos
DOC_DISPONIBLE = "DISPONIBLE"
DOC_OCUPADO = "OCUPADO"
CAMA_LIBRE = "LIBRE"
CAMA_OCUPADA = "OCUPADA"

# Mensajes de Elección (Bully Algorithm)
MSG_ELECTION = "ELECTION"      
MSG_ELECTION_OK = "ELECTION_OK" 
MSG_COORDINATOR = "COORDINATOR" 